"""add companyid to user table

Revision ID: 7f5f26b47d1e
Revises: f4c4ee6b5fc8
Create Date: 2026-01-15 17:32:23.455749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f5f26b47d1e'
down_revision: Union[str, Sequence[str], None] = 'f4c4ee6b5fc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('company_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'company_id')
    # ### end Alembic commands ###
