"""add company foreign key to lead

Revision ID: f4c4ee6b5fc8
Revises: e78e67aa875d
Create Date: 2026-01-15 17:23:41.707621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4c4ee6b5fc8'
down_revision: Union[str, Sequence[str], None] = 'e78e67aa875d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('owned_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead', 'owned_by')
    # ### end Alembic commands ###
